import React, { useEffect, useRef } from 'react';

interface RunningLightningBorderProps {
  color?: 'cyan' | 'blue' | 'indigo' | 'purple' | 'emerald';
  speedMultiplier?: number;
}

export const RunningLightningBorder: React.FC<RunningLightningBorderProps> = ({
  color = 'cyan',
  speedMultiplier = 1,
}) => {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const container = containerRef.current;
    const canvas = canvasRef.current;
    if (!container || !canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let animId: number;
    let width = 0;
    let height = 0;
    const radius = 16; // 16px corner radius matching rounded-2xl

    const resize = () => {
      if (!container || !canvas) return;
      const rect = container.getBoundingClientRect();
      width = canvas.width = Math.round(rect.width);
      height = canvas.height = Math.round(rect.height);
    };

    resize();
    const ro = new ResizeObserver(() => resize());
    ro.observe(container);

    // Color configs
    const colorMap = {
      cyan: { outer: '#06b6d4', mid: '#38bdf8', inner: '#ffffff', glow: '#00f0ff' },
      blue: { outer: '#2563eb', mid: '#60a5fa', inner: '#ffffff', glow: '#3b82f6' },
      emerald: { outer: '#059669', mid: '#34d399', inner: '#ffffff', glow: '#10b981' },
      indigo: { outer: '#4f46e5', mid: '#818cf8', inner: '#ffffff', glow: '#6366f1' },
      purple: { outer: '#7c3aed', mid: '#c084fc', inner: '#ffffff', glow: '#a855f7' },
    };
    const c = colorMap[color] || colorMap.cyan;

    // Parameterize rounded rectangle perimeter
    const getPerimeter = (w: number, h: number, r: number) => {
      const topStraight = Math.max(0, w - 2 * r);
      const rightStraight = Math.max(0, h - 2 * r);
      const bottomStraight = Math.max(0, w - 2 * r);
      const leftStraight = Math.max(0, h - 2 * r);
      const cornerArc = (Math.PI / 2) * r;
      const total = topStraight + rightStraight + bottomStraight + leftStraight + 4 * cornerArc;
      return { topStraight, rightStraight, bottomStraight, leftStraight, cornerArc, total };
    };

    const getPointAlongBorder = (
      dist: number,
      w: number,
      h: number,
      r: number
    ): { x: number; y: number; nx: number; ny: number } => {
      const p = getPerimeter(w, h, r);
      let d = ((dist % p.total) + p.total) % p.total;

      // 1. Top straight (from (r, 0) to (w - r, 0))
      if (d <= p.topStraight) {
        return { x: r + d, y: 0, nx: 0, ny: -1 };
      }
      d -= p.topStraight;

      // 2. Top-Right Corner (arc from 0 to 90 deg)
      if (d <= p.cornerArc) {
        const angle = -Math.PI / 2 + (d / p.cornerArc) * (Math.PI / 2);
        const cx = w - r;
        const cy = r;
        const x = cx + Math.cos(angle) * r;
        const y = cy + Math.sin(angle) * r;
        return { x, y, nx: Math.cos(angle), ny: Math.sin(angle) };
      }
      d -= p.cornerArc;

      // 3. Right straight (from (w, r) to (w, h - r))
      if (d <= p.rightStraight) {
        return { x: w, y: r + d, nx: 1, ny: 0 };
      }
      d -= p.rightStraight;

      // 4. Bottom-Right Corner (arc from 90 to 180 deg)
      if (d <= p.cornerArc) {
        const angle = 0 + (d / p.cornerArc) * (Math.PI / 2);
        const cx = w - r;
        const cy = h - r;
        const x = cx + Math.cos(angle) * r;
        const y = cy + Math.sin(angle) * r;
        return { x, y, nx: Math.cos(angle), ny: Math.sin(angle) };
      }
      d -= p.cornerArc;

      // 5. Bottom straight (from (w - r, h) to (r, h))
      if (d <= p.bottomStraight) {
        return { x: w - r - d, y: h, nx: 0, ny: 1 };
      }
      d -= p.bottomStraight;

      // 6. Bottom-Left Corner
      if (d <= p.cornerArc) {
        const angle = Math.PI / 2 + (d / p.cornerArc) * (Math.PI / 2);
        const cx = r;
        const cy = h - r;
        const x = cx + Math.cos(angle) * r;
        const y = cy + Math.sin(angle) * r;
        return { x, y, nx: Math.cos(angle), ny: Math.sin(angle) };
      }
      d -= p.cornerArc;

      // 7. Left straight (from (0, h - r) to (0, r))
      if (d <= p.leftStraight) {
        return { x: 0, y: h - r - d, nx: -1, ny: 0 };
      }
      d -= p.leftStraight;

      // 8. Top-Left Corner
      const angle = Math.PI + (d / p.cornerArc) * (Math.PI / 2);
      const cx = r;
      const cy = r;
      const x = cx + Math.cos(angle) * r;
      const y = cy + Math.sin(angle) * r;
      return { x, y, nx: Math.cos(angle), ny: Math.sin(angle) };
    };

    let progress1 = 0;
    let progress2 = 0.5; // second counter running bolt
    let lastTime = performance.now();

    // Spark particles generated by running lightning
    interface Spark {
      x: number;
      y: number;
      vx: number;
      vy: number;
      life: number;
      maxLife: number;
      size: number;
    }
    const sparks: Spark[] = [];

    const render = (time: number) => {
      const dt = Math.min((time - lastTime) / 1000, 0.1);
      lastTime = time;

      if (width > 0 && height > 0) {
        ctx.clearRect(0, 0, width, height);

        const pInfo = getPerimeter(width, height, radius);
        const speed = pInfo.total * 0.42 * speedMultiplier; // full loop in ~2.4 seconds

        progress1 += (speed * dt) / pInfo.total;
        if (progress1 > 1) progress1 -= 1;

        progress2 += (speed * dt) / pInfo.total;
        if (progress2 > 1) progress2 -= 1;

        const boltLength = Math.max(80, pInfo.total * 0.28); // length of the travelling lightning bolt
        const samples = 24; // segments per bolt

        const drawRunningBolt = (headProgress: number, isMain: boolean) => {
          const headDist = headProgress * pInfo.total;
          const segments: { x: number; y: number }[] = [];

          for (let i = 0; i <= samples; i++) {
            const ratio = i / samples; // 0 = tail, 1 = head
            const segDist = headDist - boltLength * (1 - ratio);
            const pt = getPointAlongBorder(segDist, width, height, radius);

            // Add organic electric lightning zig-zag jitter perpendicular to border
            // Tail has low jitter, head has high energy jitter
            const jitterAmount = (Math.random() - 0.5) * (ratio * 5 + 1.2);
            const x = pt.x + pt.nx * jitterAmount;
            const y = pt.y + pt.ny * jitterAmount;

            segments.push({ x, y });

            // Random micro lightning branch arcing out
            if (isMain && Math.random() < 0.12 && ratio > 0.4) {
              const branchDist = 8 + Math.random() * 8;
              const bx = pt.x + pt.nx * (jitterAmount + branchDist * (Math.random() > 0.5 ? 1 : -1));
              const by = pt.y + pt.ny * (jitterAmount + branchDist * (Math.random() > 0.5 ? 1 : -1));

              ctx.beginPath();
              ctx.moveTo(x, y);
              ctx.lineTo(bx, by);
              ctx.strokeStyle = c.mid;
              ctx.lineWidth = 1;
              ctx.globalAlpha = 0.7;
              ctx.stroke();
            }
          }

          if (segments.length < 2) return;

          // 1. Wide Outer Glow Line
          ctx.beginPath();
          ctx.moveTo(segments[0].x, segments[0].y);
          for (let i = 1; i < segments.length; i++) {
            ctx.lineTo(segments[i].x, segments[i].y);
          }
          ctx.strokeStyle = c.outer;
          ctx.lineWidth = isMain ? 4.5 : 3;
          ctx.lineCap = 'round';
          ctx.lineJoin = 'round';
          ctx.shadowBlur = 12;
          ctx.shadowColor = c.glow;
          ctx.globalAlpha = isMain ? 0.85 : 0.6;
          ctx.stroke();

          // 2. Middle Electric Line
          ctx.beginPath();
          ctx.moveTo(segments[0].x, segments[0].y);
          for (let i = 1; i < segments.length; i++) {
            ctx.lineTo(segments[i].x, segments[i].y);
          }
          ctx.strokeStyle = c.mid;
          ctx.lineWidth = isMain ? 2.4 : 1.8;
          ctx.shadowBlur = 6;
          ctx.shadowColor = c.mid;
          ctx.globalAlpha = 0.95;
          ctx.stroke();

          // 3. Bright White Core Filament
          ctx.beginPath();
          ctx.moveTo(segments[0].x, segments[0].y);
          for (let i = 1; i < segments.length; i++) {
            ctx.lineTo(segments[i].x, segments[i].y);
          }
          ctx.strokeStyle = c.inner;
          ctx.lineWidth = isMain ? 1.2 : 0.8;
          ctx.shadowBlur = 3;
          ctx.shadowColor = '#ffffff';
          ctx.globalAlpha = 1.0;
          ctx.stroke();

          // 4. Bright Running Lightning Head Spark Orb
          const headPt = segments[segments.length - 1];
          ctx.beginPath();
          ctx.arc(headPt.x, headPt.y, isMain ? 3.5 : 2.5, 0, Math.PI * 2);
          ctx.fillStyle = '#ffffff';
          ctx.shadowBlur = 14;
          ctx.shadowColor = '#ffffff';
          ctx.fill();

          // Spawn trailing spark particles from lightning head
          if (isMain && Math.random() < 0.6) {
            const angle = Math.random() * Math.PI * 2;
            const spd = 20 + Math.random() * 40;
            sparks.push({
              x: headPt.x,
              y: headPt.y,
              vx: Math.cos(angle) * spd,
              vy: Math.sin(angle) * spd,
              life: 1,
              maxLife: 0.3 + Math.random() * 0.3,
              size: 1.5 + Math.random() * 1.5,
            });
          }
        };

        // Draw primary travelling bolt
        drawRunningBolt(progress1, true);

        // Draw secondary trailing bolt on the opposite side
        drawRunningBolt(progress2, false);

        // Update & Render Sparks
        for (let i = sparks.length - 1; i >= 0; i--) {
          const s = sparks[i];
          s.life -= dt / s.maxLife;
          if (s.life <= 0) {
            sparks.splice(i, 1);
            continue;
          }

          s.x += s.vx * dt;
          s.y += s.vy * dt;

          ctx.beginPath();
          ctx.arc(s.x, s.y, s.size * s.life, 0, Math.PI * 2);
          ctx.fillStyle = c.mid;
          ctx.globalAlpha = s.life;
          ctx.shadowBlur = 6;
          ctx.shadowColor = c.glow;
          ctx.fill();
        }

        ctx.globalAlpha = 1.0;
        ctx.shadowBlur = 0;
      }

      animId = requestAnimationFrame(render);
    };

    animId = requestAnimationFrame(render);

    return () => {
      ro.disconnect();
      cancelAnimationFrame(animId);
    };
  }, [color, speedMultiplier]);

  return (
    <div
      ref={containerRef}
      className="absolute -inset-[2px] rounded-2xl pointer-events-none z-0 overflow-visible"
    >
      {/* 1. Hardware-Accelerated SVG Running Laser Neon Border */}
      <svg
        className="absolute inset-0 w-full h-full rounded-2xl overflow-visible pointer-events-none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <defs>
          <linearGradient id={`laser-grad-${color}`} x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#06b6d4" stopOpacity="0.1" />
            <stop offset="50%" stopColor="#38bdf8" stopOpacity="0.8" />
            <stop offset="100%" stopColor="#ffffff" stopOpacity="1" />
          </linearGradient>
          <filter id={`laser-glow-${color}`} x="-20%" y="-20%" width="140%" height="140%">
            <feGaussianBlur stdDeviation="3" result="blur" />
            <feMerge>
              <feMergeNode in="blur" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>

        {/* Static subtle background border track */}
        <rect
          x="1"
          y="1"
          width="calc(100% - 2px)"
          height="calc(100% - 2px)"
          rx="15"
          ry="15"
          fill="none"
          stroke="rgba(56, 189, 248, 0.2)"
          strokeWidth="1.5"
        />

        {/* Running Neon Laser Path with Dashoffset Animation */}
        <rect
          x="1"
          y="1"
          width="calc(100% - 2px)"
          height="calc(100% - 2px)"
          rx="15"
          ry="15"
          fill="none"
          stroke={`url(#laser-grad-${color})`}
          strokeWidth="2.5"
          strokeDasharray="90 320"
          className="animate-running-laser-stroke"
          filter={`url(#laser-glow-${color})`}
        />
      </svg>

      {/* 2. Procedural Dynamic Running Lightning Canvas with Real Crackling Electricity */}
      <canvas
        ref={canvasRef}
        className="absolute inset-0 w-full h-full rounded-2xl pointer-events-none"
      />

      {/* 3. Subtle Outer Glowing Aura */}
      <div className="absolute inset-0 rounded-2xl bg-cyan-500/10 blur-[8px] group-hover:bg-cyan-400/25 group-hover:blur-[12px] transition-all duration-300 pointer-events-none" />
    </div>
  );
};
